import type {
  OpenClawAgent,
  OpenClawProject,
  OpenClawRelationship,
  OpenClawSnapshotStats,
} from "@/lib/openclaw/types";

/**
 * Current OpenClaw snapshot — edit agents, relationships, projects, and stats here.
 * Pages and components read through `selectors.ts`.
 */
export const openclawStats: OpenClawSnapshotStats = {
  totalAgents: 8,
  specialistAgents: 6,
  supportAgents: 1,
  orchestrators: 1,
  totalProjects: 4,
  activeProjects: 4,
};

export const openclawAgents: OpenClawAgent[] = [
  {
    id: "main",
    name: "Baggo",
    emoji: "🐾",
    kind: "orchestrator",
    role: "Primary assistant and orchestrator",
    description:
      "Main OpenClaw agent for Andrew. Handles direct requests, routes work to specialists, maintains workspace context, and coordinates project work.",
    capabilities: [
      "general assistance",
      "task orchestration",
      "project coordination",
      "workspace context management",
      "delegation to specialists",
    ],
    workspace: "~/.openclaw/workspace",
    agentDir: "~/.openclaw/agents/main/agent",
    model: "openai-codex/gpt-5.4",
    channelScope: ["telegram"],
    status: "active",
    tier: "core",
    group: "orchestration",
    notes: [
      "Acts as Andrew’s main agent",
      "Can delegate to Sally, Tobi, Sam, and Riley",
    ],
  },
  {
    id: "daily-brief",
    name: "Daily Brief",
    emoji: "📰",
    kind: "support",
    role: "Periodic briefing and summary agent",
    description:
      "Support agent intended for daily summaries, briefings, and lightweight periodic updates.",
    capabilities: [
      "daily briefings",
      "summaries",
      "status aggregation",
    ],
    workspace: "~/.openclaw/workspace",
    agentDir: "~/.openclaw/agents/daily-brief/agent",
    model: "openai-codex/gpt-5.4",
    status: "active",
    tier: "support",
    group: "operations",
    notes: [
      "Uses the main workspace",
      "Not currently part of the named specialist delegation set",
    ],
  },
  {
    id: "sally",
    name: "Sally",
    emoji: "📊",
    kind: "specialist",
    role: "Market research specialist",
    description:
      "Dedicated agent for market research, niche analysis, whitespace mapping, competitor landscape work, JTBD analysis, and idea validation.",
    capabilities: [
      "market research",
      "niche selection",
      "competitor analysis",
      "JTBD analysis",
      "idea validation",
      "whitespace mapping",
    ],
    workspace: "~/.openclaw/workspace-sally",
    agentDir: "~/.openclaw/agents/sally/agent",
    model: "openai-codex/gpt-5.4",
    status: "active",
    tier: "specialist",
    group: "research-strategy",
    notes: [
      "Primary market-analysis agent",
      "Use for substantial research tasks in strategy and market selection",
    ],
  },
  {
    id: "tobi",
    name: "Tobi",
    emoji: "🚀",
    kind: "specialist",
    role: "Founder/operator and execution specialist",
    description:
      "Dedicated agent for business plans, GTM plans, MVP planning, operating plans, launch sequencing, and monetization strategy.",
    capabilities: [
      "business planning",
      "go-to-market planning",
      "execution roadmaps",
      "MVP planning",
      "operating plans",
      "monetization strategy",
    ],
    workspace: "~/.openclaw/workspace-tobi",
    agentDir: "~/.openclaw/agents/tobi/agent",
    model: "openai-codex/gpt-5.4",
    status: "active",
    tier: "specialist",
    group: "business-execution",
    notes: [
      "Best for turning ideas into executable business plans",
    ],
  },
  {
    id: "sam",
    name: "Sam",
    emoji: "🔎",
    kind: "specialist",
    role: "Deep research specialist",
    description:
      "Dedicated research agent for source gathering, evidence mapping, broad scans, topic exploration, and research support for later analysis.",
    capabilities: [
      "deep research",
      "source gathering",
      "evidence mapping",
      "framework scans",
      "topic exploration",
    ],
    workspace: "~/.openclaw/workspace-sam",
    agentDir: "~/.openclaw/agents/sam/agent",
    model: "openai-codex/gpt-5.4",
    status: "active",
    tier: "specialist",
    group: "research-evidence",
    notes: [
      "Best for broad evidence collection before synthesis or planning",
    ],
  },
  {
    id: "riley",
    name: "Riley",
    emoji: "🎨",
    kind: "specialist",
    role: "Web design and frontend architecture specialist",
    description:
      "Dedicated agent for website architecture, sitemap design, landing pages, UI systems, and React/Next.js website design.",
    capabilities: [
      "web design",
      "information architecture",
      "sitemap design",
      "landing pages",
      "design systems",
      "React",
      "Next.js",
      "dashboard UX",
    ],
    workspace: "~/.openclaw/workspace-riley",
    agentDir: "~/.openclaw/agents/riley/agent",
    model: "openai-codex/gpt-5.4",
    status: "active",
    tier: "specialist",
    group: "design-frontend",
    notes: [
      "Recently added as the dedicated web-design specialist",
      "Installed skills include SuperDesign, design-system-creation, tailwind-design-system, and sovereign-accessibility-auditor",
    ],
  },
  {
    id: "leroy",
    name: "Leroy",
    emoji: "📚",
    kind: "specialist",
    role: "Ingestion and repository specialist",
    description:
      "Dedicated ingestion agent for the Personal Knowledgebase. Handles source detection, fetching, extraction, normalization, fanout, and lightweight enrichment before structured persistence into Crashboard.",
    capabilities: [
      "source detection",
      "content extraction",
      "normalization",
      "fanout",
      "summary generation",
      "keyword enrichment",
      "structured ingestion",
    ],
    workspace: "~/.openclaw/workspace-leroy",
    agentDir: "~/.openclaw/agents/leroy/agent",
    model: "openai-codex/gpt-5.4",
    status: "active",
    tier: "specialist",
    group: "ingestion-knowledgebase",
    notes: [
      "Dedicated Personal Knowledgebase ingestion specialist",
      "Handles article, PDF, YouTube, and X/Twitter extraction workflows",
    ],
    tags: ["knowledgebase", "ingestion", "structured-payloads"],
  },
  {
    id: "ian",
    name: "Ian",
    emoji: "🛠️",
    kind: "specialist",
    role: "Expert coding and implementation agent",
    description:
      "Dedicated coding agent for local repositories and dashboard implementation work. Focuses on understanding before editing, making minimal high-leverage changes, and keeping project work clean and reviewable.",
    capabilities: [
      "software engineering",
      "local repository work",
      "dashboard implementation",
      "refactoring",
      "code review",
      "technical planning",
    ],
    workspace: "~/.openclaw/workspace-ian",
    agentDir: "~/.openclaw/agents/ian/agent",
    model: "openai-codex/gpt-5.4",
    status: "active",
    tier: "specialist",
    group: "engineering-implementation",
    notes: [
      "Created as Andrew’s expert coding agent",
      "Works directly in local codebases and stops for review before pushes",
    ],
    tags: ["coding", "implementation", "crashboard"],
  },
];

export const openclawRelationships: OpenClawRelationship[] = [
  {
    id: "main-manages-sally",
    fromAgentId: "main",
    toAgentId: "sally",
    type: "delegates_to",
    label: "Delegates market research work",
  },
  {
    id: "main-manages-tobi",
    fromAgentId: "main",
    toAgentId: "tobi",
    type: "delegates_to",
    label: "Delegates business planning and execution work",
  },
  {
    id: "main-manages-sam",
    fromAgentId: "main",
    toAgentId: "sam",
    type: "delegates_to",
    label: "Delegates deep research and source gathering",
  },
  {
    id: "main-manages-riley",
    fromAgentId: "main",
    toAgentId: "riley",
    type: "delegates_to",
    label: "Delegates web design and frontend architecture work",
  },
  {
    id: "main-supports-daily-brief",
    fromAgentId: "main",
    toAgentId: "daily-brief",
    type: "supports",
    label: "Shared workspace / support function",
  },
  {
    id: "main-manages-leroy",
    fromAgentId: "main",
    toAgentId: "leroy",
    type: "delegates_to",
    label: "Delegates ingestion, extraction, and repository normalization work",
  },
  {
    id: "main-manages-ian",
    fromAgentId: "main",
    toAgentId: "ian",
    type: "delegates_to",
    label: "Delegates coding, implementation, and local repository work",
  },
  {
    id: "ian-works-with-riley",
    fromAgentId: "ian",
    toAgentId: "riley",
    type: "works_with",
    label: "Pairs implementation with dashboard and frontend design work",
  },
  {
    id: "leroy-specializes-for-crashboard",
    fromAgentId: "leroy",
    toAgentId: "main",
    type: "specializes_for",
    label: "Specialist lane for Personal Knowledgebase ingestion under Baggo",
  },
];

export const openclawProjects: OpenClawProject[] = [
  {
    id: "crashboard",
    name: "Crashboard",
    status: "active",
    stage: "architecture-and-design",
    category: "personal website + dashboard",
    summary:
      "Andrew’s personal website and private authenticated dashboard project, built with Next.js, Tailwind, shadcn/ui, and Supabase auth.",
    tags: [
      "nextjs",
      "dashboard",
      "supabase",
      "personal-site",
      "shadcn",
      "react",
    ],
    linkedAgentIds: ["main", "riley"],
    notes: [
      "Public + private split is intentional",
      "Existing Supabase auth must be preserved",
      "Current design direction is minimalist and professional",
    ],
  },
  {
    id: "ai-governance-readiness",
    name: "AI Governance / Readiness",
    status: "active",
    stage: "post-research-pre-build",
    category: "content-led venture",
    summary:
      "A content-led venture around AI planning, governance, trust, maturity, and data strategy. Market analysis and execution plan are complete.",
    tags: [
      "ai",
      "governance",
      "readiness",
      "trust",
      "content",
      "strategy",
    ],
    linkedAgentIds: ["main", "sally", "tobi", "sam"],
    notes: [
      "Project is currently unnamed",
      "Ready for flagship asset design, site architecture, and first content work",
    ],
  },
  {
    id: "wags-and-wanders",
    name: "Wags and Wanders",
    status: "active",
    stage: "validated-idea",
    category: "niche business concept",
    summary:
      "A narrow, high-trust dog travel planning concept focused on helping owners plan international travel with dogs without missing legal or airline requirements.",
    tags: [
      "dog-travel",
      "validation",
      "planning",
      "travel-intelligence",
      "niche-market",
    ],
    linkedAgentIds: ["main", "sally", "tobi"],
    notes: [
      "Preliminary market validation completed",
      "Ready for more structured project work, data strategy, and eventual build planning",
    ],
  },
  {
    id: "personal-knowledgebase",
    name: "Personal Knowledgebase",
    status: "active",
    stage: "repository-first-buildout",
    category: "private repository + future knowledgebase",
    summary:
      "Private repository system for captured content from Telegram, with Leroy handling extraction and structured ingestion into Crashboard before later semantic retrieval layers are added.",
    tags: [
      "knowledgebase",
      "repository",
      "telegram-capture",
      "leroy",
      "supabase",
      "rag-later",
    ],
    linkedAgentIds: ["main", "leroy", "ian", "riley"],
    notes: [
      "Repository usefulness comes before embeddings and semantic retrieval",
      "Crashboard is the implementation home for the backend and dashboard UI",
      "Telegram hashtags should become first-class user tags",
    ],
  },
];
