import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ExternalLink } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { getIntelligenceDocument } from "@/lib/intelligence/signal-data";

export const metadata: Metadata = { title: "Evidence Document · Trend Intelligence" };
export const dynamic = "force-dynamic";

export default async function IntelligenceDocumentPage({ params }: { params: Promise<{ documentId: string }> }) {
  const { documentId } = await params;
  const data = await getIntelligenceDocument(documentId);
  if (!data) notFound();
  const document = data.document as Record<string, unknown>;
  const sourceUrl = String(document.canonical_url ?? document.original_url ?? "#");
  return <article className="space-y-8 pb-14">
    <header className="border-b border-foreground/80 pb-7"><div className="flex flex-wrap gap-2"><Badge>{String(document.source_type).replaceAll("_", " ")}</Badge><Badge variant="outline">{String(document.extraction_method).replaceAll("_", " ")}</Badge></div><h1 className="mt-5 max-w-5xl font-heading text-4xl font-semibold leading-tight">{String(document.title ?? "Untitled evidence")}</h1><p className="mt-4 max-w-4xl text-base leading-7 text-muted-foreground">{String(document.summary_short ?? "")}</p><div className="mt-5 flex flex-wrap items-center gap-5 font-mono text-xs text-muted-foreground">{document.publisher_name ? <span>{String(document.publisher_name)}</span> : null}{document.published_at ? <span>{String(document.published_at).slice(0, 10)}</span> : null}<span>{data.segments.length} segments</span><a href={sourceUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 font-sans font-medium text-foreground hover:text-accent">Open original <ExternalLink className="size-3" /></a></div></header>
    <section className="grid gap-5 lg:grid-cols-[1.5fr_0.8fr]"><div><div className="border-b border-foreground/80 pb-3"><p className="editorial-kicker">Article grain</p><h2 className="mt-1 font-heading text-2xl font-semibold">Retained segments</h2></div><div className="border-x border-b border-border">{data.segments.map((segment) => <section key={String(segment.id)} className="border-t border-border bg-card p-4"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{String(segment.segment_type)}</Badge><span className="font-mono text-xs text-muted-foreground">segment {String(segment.segment_index)}</span>{segment.outbound_url ? <a href={String(segment.outbound_url)} target="_blank" rel="noopener noreferrer" className="ml-auto inline-flex items-center gap-1 text-xs font-medium">Article link <ExternalLink className="size-3" /></a> : null}</div>{segment.title ? <h3 className="mt-3 font-heading text-xl font-semibold">{String(segment.title)}</h3> : null}<p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{String(segment.content_text)}</p></section>)}</div></div><aside className="space-y-5"><div className="border border-border bg-card p-4"><p className="editorial-kicker">Canonical concepts</p><div className="mt-4 flex flex-wrap gap-2">{data.concepts.map((row, index) => { const item = row as unknown as { intelligence_concepts: Record<string, unknown> | null }; const concept = item.intelligence_concepts ?? {}; return <Link key={`${concept.id}-${index}`} href={`/dashboard/intelligence/trends/${encodeURIComponent(`concept:${concept.id}`)}`}><Badge variant="secondary">{String(concept.canonical_label)}</Badge></Link>; })}{!data.concepts.length ? <p className="text-sm text-muted-foreground">No resolved concepts.</p> : null}</div></div><div className="border border-border bg-card p-4"><p className="editorial-kicker">Entities</p><div className="mt-4 space-y-3">{data.entities.map((row, index) => { const item = row as unknown as { role: string; intelligence_entities: Record<string, unknown> | null }; const entity = item.intelligence_entities ?? {}; return <div key={`${entity.id}-${index}`} className="border-b border-border pb-2 last:border-0"><Link href={`/dashboard/intelligence/trends/${encodeURIComponent(`entity:${entity.id}`)}`} className="font-medium hover:text-accent">{String(entity.canonical_name)}</Link><p className="text-xs text-muted-foreground">{item.role} · {String(entity.entity_type).replaceAll("_", " ")}</p></div>; })}</div></div></aside></section>
    {data.evidence.length ? <section><div className="border-b border-foreground/80 pb-3"><p className="editorial-kicker">Extracted actions</p><h2 className="mt-1 font-heading text-2xl font-semibold">Events supported by this document</h2></div><div className="border-x border-b border-border">{data.evidence.map((row, index) => { const item = row as unknown as { evidence_role: string; evidence_text: string | null; intelligence_events: Record<string, unknown> | null }; const event = item.intelligence_events ?? {}; return <Link key={`${event.id}-${index}`} href={`/dashboard/intelligence/events/${event.id}`} className="block border-t border-border bg-card p-4 hover:bg-muted/50"><Badge variant="outline">{String(event.event_type).replaceAll("_", " ")}</Badge><h3 className="mt-2 font-medium">{String(event.title)}</h3><p className="mt-1 text-sm text-muted-foreground">{item.evidence_text}</p></Link>; })}</div></section> : null}
  </article>;
}
